const users = [
  {
    name: "Mayur Kamble",
    email: "mayurkamble@gmail.com",
    profession: "Full Stack Developer",
    bio: "Building scalable web applications with modern technologies. Open source enthusiast and mentor",
    profilePic: "https://avatars.githubusercontent.com/u/143837952?v=4",
    coverPic: "https://boards.holopin.io/mayurk224",
    followers: 2450,
    following: 389,
    projects: 13,
    isVerified: true,
    skills: ["Figma", "Sketch", "Adobe XD", "Prototyping", "User Research", "Wireframing", "Design Systems", "HTML", "CSS", "JavaScript"],
    location: "Nagpur, Maharashtra",
    social: {
      github: "https://github.com/mayurk224",
      instagram: "https://www.instagram.com/mayurkamble_02?igsh=cm1iNGRmZzcxdm83",
      linkedin: "https://www.linkedin.com/in/mayur-kamble-a51348286",
    },
    experience: [
      {
        company: "TechFlow Inc.",
        position: "Senior UX Designer",
        location: "New York, NY",
        description: "Led redesign of mobile app resulting in 45% increase in user engagement and 30% reduction in bounce rate",
        duration: "2020 - Present",
      },
      {
        company: "DesignHub",
        position: "UX Designer",
        location: "New York, NY",
        description: "Collaborated with cross-functional teams to deliver user-centric designs for B2B SaaS platform",
        duration: "2017 - 2020",
      },
    ],
  },
  {
    name: "Sarah Mitchell",
    email: "sarah.mitchell@gmail.com",
    profession: "UX/UI Designer",
    bio: "Creating delightful digital experiences through user-centered design and interactive prototypes",
    profilePic: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg",
    coverPic: "https://images.pexels.com/photos/1103970/pexels-photo-1103970.jpeg",
    followers: 2450,
    following: 389,
    projects: 42,
    isVerified: true,
    skills: ["Figma", "Sketch", "Adobe XD", "Prototyping", "User Research", "Wireframing", "Design Systems", "HTML", "CSS", "JavaScript"],
    location: "New York, NY",
    social: {
      github: "https://github.com/sarahmitchell",
      instagram: "https://instagram.com/sarahmitchell",
      linkedin: "https://linkedin.com/in/sarahmitchell",
    },
    experience: [
      {
        company: "TechFlow Inc.",
        position: "Senior UX Designer",
        location: "New York, NY",
        description: "Led redesign of mobile app resulting in 45% increase in user engagement and 30% reduction in bounce rate",
        duration: "2020 - Present",
      },
      {
        company: "DesignHub",
        position: "UX Designer",
        location: "New York, NY",
        description: "Collaborated with cross-functional teams to deliver user-centric designs for B2B SaaS platform",
        duration: "2017 - 2020",
      },
    ],
  },
  {
    name: "Marcus Chen",
    email: "marcus.chen@gmail.com",
    profession: "Full Stack Developer",
    bio: "Building scalable web applications with modern technologies. Open source enthusiast and mentor",
    profilePic: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg",
    coverPic: "https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg",
    followers: 3890,
    following: 567,
    projects: 35,
    isVerified: true,
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS", "Docker", "GraphQL", "Next.js", "MongoDB", "Redis"],
    location: "San Francisco, CA",
    social: {
      github: "https://github.com/marcuschen",
      instagram: "https://instagram.com/marcuschen",
      linkedin: "https://linkedin.com/in/marcuschen",
    },
    experience: [
      {
        company: "CloudScale Systems",
        position: "Lead Full Stack Engineer",
        location: "San Francisco, CA",
        description: "Architected microservices infrastructure serving 2M+ users with 99.9% uptime. Reduced API response time by 60%",
        duration: "2019 - Present",
      },
      {
        company: "StartupLab",
        position: "Full Stack Developer",
        location: "San Francisco, CA",
        description: "Developed MVP for 3 successful startups, implementing features from database to frontend",
        duration: "2016 - 2019",
      },
    ],
  },
  {
    name: "Elena Rodriguez",
    email: "elena.rodriguez@gmail.com",
    profession: "Data Scientist",
    bio: "Transforming data into actionable insights. Passionate about ML, AI, and solving complex problems",
    profilePic: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg",
    coverPic: "https://images.pexels.com/photos/1089438/pexels-photo-1089438.jpeg",
    followers: 1820,
    following: 234,
    projects: 22,
    isVerified: true,
    skills: ["Python", "Machine Learning", "TensorFlow", "PyTorch", "SQL", "R", "Data Visualization", "Pandas", "NumPy", "Scikit-learn"],
    location: "Austin, TX",
    social: {
      github: "https://github.com/elenarodriguez",
      instagram: "https://instagram.com/elenarodriguez",
      linkedin: "https://linkedin.com/in/elenarodriguez",
    },
    experience: [
      {
        company: "DataVision AI",
        position: "Senior Data Scientist",
        location: "Austin, TX",
        description: "Built predictive models that improved customer retention by 35% and increased revenue by $2M annually",
        duration: "2021 - Present",
      },
      {
        company: "Analytics Pro",
        position: "Data Scientist",
        location: "Austin, TX",
        description: "Developed recommendation system using collaborative filtering, increasing user engagement by 28%",
        duration: "2018 - 2021",
      },
    ],
  },
  {
    name: "David Kim",
    email: "david.kim@gmail.com",
    profession: "DevOps Engineer",
    bio: "Automating infrastructure and streamlining deployments. Cloud native advocate and Kubernetes expert",
    profilePic: "https://images.pexels.com/photos/1516680/pexels-photo-1516680.jpeg",
    coverPic: "https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg",
    followers: 1456,
    following: 412,
    projects: 41,
    isVerified: false,
    skills: ["Kubernetes", "Docker", "AWS", "Terraform", "Jenkins", "CI/CD", "Linux", "Python", "Bash", "Ansible"],
    location: "Seattle, WA",
    social: {
      github: "https://github.com/davidkim",
      instagram: "https://instagram.com/davidkim",
      linkedin: "https://linkedin.com/in/davidkim",
    },
    experience: [
      {
        company: "CloudNative Tech",
        position: "DevOps Engineer",
        location: "Seattle, WA",
        description: "Implemented CI/CD pipelines reducing deployment time from 2 hours to 15 minutes. Managed 200+ microservices",
        duration: "2020 - Present",
      },
      {
        company: "ServerScale",
        position: "Systems Administrator",
        location: "Seattle, WA",
        description: "Automated infrastructure provisioning and monitoring for 50+ production servers",
        duration: "2017 - 2020",
      },
    ],
  },
  {
    name: "Priya Sharma",
    email: "priya.sharma@gmail.com",
    profession: "Mobile Developer",
    bio: "Crafting beautiful native mobile experiences. iOS and Android specialist with a focus on performance",
    profilePic: "https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg",
    coverPic: "https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg",
    followers: 2145,
    following: 298,
    projects: 33,
    isVerified: true,
    skills: ["Swift", "Kotlin", "React Native", "Flutter", "iOS", "Android", "Firebase", "REST APIs", "Git", "UI/UX"],
    location: "Toronto, ON",
    social: {
      github: "https://github.com/priyasharma",
      instagram: "https://instagram.com/priyasharma",
      linkedin: "https://linkedin.com/in/priyasharma",
    },
    experience: [
      {
        company: "MobileFirst Solutions",
        position: "Senior Mobile Developer",
        location: "Toronto, ON",
        description: "Led development of award-winning fitness app with 500K+ downloads and 4.8 star rating",
        duration: "2019 - Present",
      },
      {
        company: "AppCraft Studio",
        position: "Mobile Developer",
        location: "Toronto, ON",
        description: "Developed 12+ mobile applications for various clients across iOS and Android platforms",
        duration: "2016 - 2019",
      },
    ],
  },
  {
    name: "James Wilson",
    email: "james.wilson@gmail.com",
    profession: "Cybersecurity Analyst",
    bio: "Protecting digital assets and infrastructure. Ethical hacker and security researcher",
    profilePic: "https://images.pexels.com/photos/1024311/pexels-photo-1024311.jpeg",
    coverPic: "https://images.pexels.com/photos/1181298/pexels-photo-1181298.jpeg",
    followers: 987,
    following: 156,
    projects: 18,
    isVerified: false,
    skills: ["Penetration Testing", "Network Security", "Python", "Cryptography", "SIEM", "Incident Response", "Linux", "Wireshark", "Metasploit", "Security Auditing"],
    location: "Washington, DC",
    social: {
      github: "https://github.com/jameswilson",
      instagram: "https://instagram.com/jameswilson",
      linkedin: "https://linkedin.com/in/jameswilson",
    },
    experience: [
      {
        company: "SecureNet Corp",
        position: "Cybersecurity Analyst",
        location: "Washington, DC",
        description: "Conducted security assessments and penetration tests for Fortune 500 clients, identifying critical vulnerabilities",
        duration: "2021 - Present",
      },
      {
        company: "DefendIT Solutions",
        position: "Security Consultant",
        location: "Washington, DC",
        description: "Implemented security protocols and trained teams on best practices for data protection",
        duration: "2018 - 2021",
      },
    ],
  },
  {
    name: "Aisha Patel",
    email: "aisha.patel@gmail.com",
    profession: "Product Manager",
    bio: "Driving product strategy and innovation. Bridging the gap between business and technology",
    profilePic: "https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg",
    coverPic: "https://images.pexels.com/photos/1181354/pexels-photo-1181354.jpeg",
    followers: 3210,
    following: 445,
    projects: 45,
    isVerified: true,
    skills: ["Product Strategy", "Agile", "User Stories", "Market Research", "Roadmapping", "A/B Testing", "Analytics", "SQL", "JIRA", "Stakeholder Management"],
    location: "London, UK",
    social: {
      github: "https://github.com/aishapatel",
      instagram: "https://instagram.com/aishapatel",
      linkedin: "https://linkedin.com/in/aishapatel",
    },
    experience: [
      {
        company: "InnovateTech",
        position: "Senior Product Manager",
        location: "London, UK",
        description: "Led product team of 15 to launch SaaS platform generating £5M ARR in first year. Increased user retention by 40%",
        duration: "2020 - Present",
      },
      {
        company: "GrowthHub",
        position: "Product Manager",
        location: "London, UK",
        description: "Managed product lifecycle from ideation to launch for 3 successful B2B products",
        duration: "2017 - 2020",
      },
    ],
  },
  {
    name: "Alex Thompson",
    email: "alex.thompson@gmail.com",
    profession: "Frontend Developer",
    bio: "Pixel-perfect frontend implementations. Performance optimization and accessibility advocate",
    profilePic: "https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg",
    coverPic: "https://images.pexels.com/photos/1181292/pexels-photo-1181292.jpeg",
    followers: 1678,
    following: 321,
    projects: 27,
    isVerified: false,
    skills: ["JavaScript", "React", "Vue.js", "CSS", "HTML", "Tailwind CSS", "Webpack", "TypeScript", "SASS", "Responsive Design"],
    location: "Berlin, Germany",
    social: {
      github: "https://github.com/alexthompson",
      instagram: "https://instagram.com/alexthompson",
      linkedin: "https://linkedin.com/in/alexthompson",
    },
    experience: [
      {
        company: "DigitalCraft GmbH",
        position: "Frontend Developer",
        location: "Berlin, Germany",
        description: "Built responsive web applications with focus on performance, achieving 95+ Lighthouse scores consistently",
        duration: "2019 - Present",
      },
      {
        company: "WebStudio",
        position: "Junior Frontend Developer",
        location: "Berlin, Germany",
        description: "Developed interactive UI components and maintained design system for e-commerce platform",
        duration: "2017 - 2019",
      },
    ],
  },
  {
    name: "Maria Santos",
    email: "maria.santos@gmail.com",
    profession: "Content Strategist",
    bio: "Telling compelling stories through content. SEO expert and digital marketing enthusiast",
    profilePic: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg",
    coverPic: "https://images.pexels.com/photos/1181533/pexels-photo-1181533.jpeg",
    followers: 4567,
    following: 789,
    projects: 39,
    isVerified: true,
    skills: ["Content Strategy", "SEO", "Copywriting", "Social Media", "Google Analytics", "Marketing Automation", "Email Marketing", "WordPress", "Content Management", "Brand Strategy"],
    location: "Miami, FL",
    social: {
      github: "https://github.com/mariasantos",
      instagram: "https://instagram.com/mariasantos",
      linkedin: "https://linkedin.com/in/mariasantos",
    },
    experience: [
      {
        company: "ContentFirst Agency",
        position: "Lead Content Strategist",
        location: "Miami, FL",
        description: "Developed content strategies for 20+ brands, increasing organic traffic by 150% and engagement by 85%",
        duration: "2020 - Present",
      },
      {
        company: "Digital Marketing Pro",
        position: "Content Strategist",
        location: "Miami, FL",
        description: "Created and executed content calendars, managed social media campaigns with ROI of 300%",
        duration: "2017 - 2020",
      },
    ],
  },
  {
    name: "Ryan Foster",
    email: "ryan.foster@gmail.com",
    profession: "Backend Engineer",
    bio: "Building robust APIs and scalable systems. Database optimization and microservices architecture specialist",
    profilePic: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg",
    coverPic: "https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg",
    followers: 1234,
    following: 267,
    projects: 15,
    isVerified: false,
    skills: ["Node.js", "Python", "Java", "PostgreSQL", "Redis", "Microservices", "REST APIs", "GraphQL", "AWS", "Elasticsearch"],
    location: "Boston, MA",
    social: {
      github: "https://github.com/ryanfoster",
      instagram: "https://instagram.com/ryanfoster",
      linkedin: "https://linkedin.com/in/ryanfoster",
    },
    experience: [
      {
        company: "ScaleUp Systems",
        position: "Backend Engineer",
        location: "Boston, MA",
        description: "Optimized database queries reducing response time by 70%. Built microservices handling 10M+ requests daily",
        duration: "2021 - Present",
      },
      {
        company: "TechCore Inc",
        position: "Junior Backend Developer",
        location: "Boston, MA",
        description: "Developed RESTful APIs and integrated third-party services for financial application",
        duration: "2018 - 2021",
      },
    ],
  },
];

export default users;
